// Generated by Wrangler on Fri Jun 28 2024 01:06:54 GMT+0200 (heure d’été d’Europe centrale)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	SOLANA_RPC: string;
	FEE_ADDRESS: string;
	NEXT_PUBLIC_API_URL: string;
}
