// Generated by Wrangler on Wed Jun 26 2024 02:30:05 GMT+0200 (heure d’été d’Europe centrale)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	SOLANA_RPC: string;
}
