// Generated by Wrangler on Sat Jun 29 2024 01:35:03 GMT+0200 (heure d’été d’Europe centrale)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	SOLANA_RPC: string;
	FEE_ADDRESS: string;
	NEXT_PUBLIC_BASE_URL: string;
	NEXT_PUBLIC_DEFAULT_TO: string;
}
